export default [
  {
    ignores:
      [
        'node_modules',
      ],
  },
  {
    files:
      [
        '**/*.js',
        '**/*.mjs',
      ],
    languageOptions:
      {
        ecmaVersion:
          'latest',
        sourceType:
          'module',
      },
    rules:
      {
        'no-unused-vars':
          'error',
        semi: [
          'error',
          'always',
        ],
        eqeqeq:
          [
            'error',
            'always',
          ],
        'prefer-const':
          [
            'error',
            {
              destructuring:
                'any',
              ignoreReadBeforeAssign: false,
            },
          ],
      },
  },
];
